import Head from 'next/head'
import LoanCalculator from '../components/LoanCalculator'
import { FcHome } from 'react-icons/fc'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <nav className="flex items-center gap-3 p-5 ">
          <FcHome className="text-2xl" />
          <h1 className="text-xl font-bold">Property Calculator</h1>
        </nav>
        <LoanCalculator />
      </main>
    </div>
  )
}
